### ISSUE TITLE
Discuss: Release plan

### ISSUE THREAD

**Issue by jrochkind** [projectblacklight/blacklight_advanced_search#15]
Trying to wrap my head around what's going on with the various pieces of code, and how to do a sensible release plan. Appreciate feedback, esp from @cbeer who is committer on much of the not-yet-released code. 

## State of the code

The current latest `blacklight_advanced_search` release is 2.1.1 from July 29 2013. That is one day before the release of Blacklight 4.3.0.  The gemspec for 2.1.1 says ` "blacklight", "~> 4.0"`, which says it expects to work with all Blacklight 4.x, but who knows if that's actually true. 

There are three outstanding pull requests in the github issues here. One of them (#12) says it's about removing deprecated uses, but also changes the gemspec to require at least Blacklight 4.7.

There's also a [blacklight-4.7+](https://github.com/projectblacklight/blacklight_advanced_search/tree/blacklight-4.7+) branch here in `blacklight_advanced_search`, which does have commits that are not in master, and which I _think_ is not represented in any pull requests. 

There's also a more recent [blacklight5](https://github.com/projectblacklight/blacklight_advanced_search/tree/blacklight5) branch, also apparently not merged into master or represented in any PR's. 

## My plan

* 1: Last Blacklight 4.x release
    * Try to merge all outstanding pull requests into master.
    * Try to merge existing `blacklight-4.7+` branch into master. 
    * Do some code review on each one, don't just blindly merge
    * Give up on ones I have trouble with
    *  Release a `blacklight_advanced_search` 2.2, which is for Blacklight 4.7 and theoretical future 4.x  Last 4.x release, which requires at least 4.7, cause that's what the existing pull requests/branches want, although I'm not certain why. 

* 2: blacklight5 release
    * then, merge blacklight5 branch into master. 
    * release a `blacklight_advanced_search` 5.x, with gemspec set to expect to work with any Blacklight 5.x.  Yep, major version number sync, 5=5. 

## Good?

If anyone has any suggestions or sees any problems, and especially if you have information or understanding of what's going on that I am missing that suggests modifying this plan, please let me know!

**Comment by atz** [comment]
After 2+ years, I'm guessing this is settled history.
